apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alkfet

resources:
- namespace.yaml
- secrets.yaml
- dataaccess.yaml
- webapi.yaml
- mcp.yaml
- webui.yaml

images:
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newTag: fc2f6656a752aef9da90e044370334a8d71fedae
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newTag: fd24fd4a94149e683634537f0ad19371d6557315
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newTag: fd24fd4a94149e683634537f0ad19371d6557315
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newTag: fd24fd4a94149e683634537f0ad19371d6557315
