apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alkfet

resources:
- namespace.yaml
- secrets.yaml
- dataaccess.yaml
- webapi.yaml
- mcp.yaml
- webui.yaml

images:
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newTag: ce22830eebe893790a327714c59a0211ad6d67fd
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newTag: ce22830eebe893790a327714c59a0211ad6d67fd
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newTag: ce22830eebe893790a327714c59a0211ad6d67fd
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newTag: ce22830eebe893790a327714c59a0211ad6d67fd
