apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alkfet

resources:
- namespace.yaml
- secrets.yaml
- dataaccess.yaml
- webapi.yaml
- mcp.yaml
- webui.yaml

images:
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-dataaccess
  newTag: a6a467a43cac60e51c099111f06b9e397e0f5135
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-mcp
  newTag: a6a467a43cac60e51c099111f06b9e397e0f5135
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webapi
  newTag: a6a467a43cac60e51c099111f06b9e397e0f5135
- name: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newName: ghcr.io/mendelevian-hub/alkfet-book-manager-webui
  newTag: a6a467a43cac60e51c099111f06b9e397e0f5135
