server {
  listen 80;
  server_name _;

  location / {
    root /usr/share/nginx/html;
    try_files $uri $uri/ /index.html;
  }

  # K8s-ben a service neve: alkfet-webapi (deployment/prod/webapi.yaml)
  location /api/ {
    proxy_pass http://alkfet-webapi:8080/api/;
  }
}
